### ISSUE TITLE
fix `message too long` error

### ISSUE THREAD

**Issue by bilalcaliskan** [bilalcaliskan/syn-flood#6]
Throws below exception while we are trying to send 1048576 bytes for each packet but works fine on 104 bytes. Is there a way to bypass or increase that limit?

```
sudo /usr/local/go/bin/go run cmd/syn-flood/main.go
panic: write ip 0.0.0.0->213.238.175.187: sendmsg: message too long

goroutine 1 [running]:
github.com/bilalcaliskan/syn-flood/pkg/raw.StartFlooding(0x64019c, 0xf, 0x1bb, 0x28f5)
        /home/joshsagredo/go/src/github.com/bilalcaliskan/syn-flood/pkg/raw/raw.go:92 +0x675
main.main()
        /home/joshsagredo/go/src/github.com/bilalcaliskan/syn-flood/cmd/syn-flood/main.go:21 +0x51
exit status 2
```

**Comment by bilalcaliskan** [comment]
1400 byte is enough
